on:
  workflow_dispatch:
    # Enable manual trigger for this action.
    inputs:
      version:
        description: Bundle version.
        required: true

jobs:
  generate-bundle:
    runs-on: ubuntu-latest
    name: Generate operator bundle
    steps:
      - uses: actions/checkout@v2
      - name: olm-bundle action
        id: bundle
        uses: darkowlzz/olm-bundle@master
        with:
          outputDir: opendatahub-operator/${{ github.event.inputs.version }}
          channels: stable,rolling
          package: opendatahub-operator
          operatorRepo: https://github.com/opendatahub-io/opendatahub-operator
          operatorBranch: feature/update-sdk
          operatorManifestsDir: bundle/manifests
      - name: bundle tree output
        run: echo "${{ steps.bundle.outputs.tree }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.4.0
